// Code generated by mockery v2.10.4. DO NOT EDIT.

package producers

import (
	"github.com/ohmpatel1997/vwap/producers"
	mock "github.com/stretchr/testify/mock"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// VWAP provides a mock function with given fields:
func (_m *Producer) VWAP() producers.VWAP {
	ret := _m.Called()

	var r0 producers.VWAP
	if rf, ok := ret.Get(0).(func() producers.VWAP); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(producers.VWAP)
		}
	}

	return r0
}
