// Code generated by mockery v2.10.4. DO NOT EDIT.

package producers

import (
	entity "github.com/ohmpatel1997/vwap/entity"
	mock "github.com/stretchr/testify/mock"
)

// VWAP is an autogenerated mock type for the VWAP type
type VWAP struct {
	mock.Mock
}

// Send provides a mock function with given fields: msg
func (_m *VWAP) Send(msg *entity.VWAP) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.VWAP) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
