// Code generated by mockery v2.10.4. DO NOT EDIT.

package consumers

import (
	"github.com/ohmpatel1997/vwap/entity"
	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

// Consume provides a mock function with given fields: message
func (_m *Consumer) Consume(message *entity.Match) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
