// Code generated by mockery v2.10.4. DO NOT EDIT.

package usecase

import (
	entity "github.com/ohmpatel1997/vwap/entity"
	mock "github.com/stretchr/testify/mock"
)

// MatchUseCase is an autogenerated mock type for the MatchUseCase type
type MatchUseCase struct {
	mock.Mock
}

// UpdateVWAP provides a mock function with given fields: match
func (_m *MatchUseCase) UpdateVWAP(match *entity.Match) error {
	ret := _m.Called(match)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Match) error); ok {
		r0 = rf(match)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
