// Code generated by mockery v2.10.4. DO NOT EDIT.

package repository

import (
	"github.com/ohmpatel1997/vwap/repository"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Match provides a mock function with given fields:
func (_m *Repository) Match() repository.MatchRepository {
	ret := _m.Called()

	var r0 repository.MatchRepository
	if rf, ok := ret.Get(0).(func() repository.MatchRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.MatchRepository)
		}
	}

	return r0
}
